apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: cluster1
  project: awsdemo
spec:
  blueprintConfig:
    name: default
    version: latest
  cloudCredentials: aws-cloud-credential
  config:
    addons:
    - name: kube-proxy
      version: latest
    - name: vpc-cni
      version: latest
    - name: coredns
      version: latest
    iam:
      serviceAccounts:
      - attachPolicy:
          Statement:
          - Action:
            - ec2:DescribeVolumes
            - ec2:DescribeSnapshots
            - ec2:CreateTags
            - ec2:CreateVolume
            - ec2:CreateSnapshot
            - ec2:DeleteSnapshot
            Effect: Allow
            Resource: '*'
          - Action:
            - s3:GetObject
            - s3:DeleteObject
            - s3:PutObject
            - s3:AbortMultipartUpload
            - s3:ListMultipartUploadParts
            Effect: Allow
            Resource:
            - arn:aws:s3:::s3backupbucket/*
          - Action:
            - s3:ListBucket
            Effect: Allow
            Resource:
            - arn:aws:s3:::s3backupbucket
          Version: "2012-10-17"
        metadata:
          name: velero-rafay
          namespace: rafay-system
        roleOnly: true
        roleName: rafay-backuprestore-role
      withOIDC: true
    managedNodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 2
      instanceType: t3.large
      maxSize: 2
      minSize: 1
      name: ng-1
    metadata:
      name: cluster1
      region: us-west-2
      tags:
        email: user@rafay.co
        env: qa
      version: latest
  type: aws-eks
