kind: Cluster
metadata:
  name: cluster1
  project: poc
spec:
  blueprint: default
  cloudprovider: aws-cloud-credential
  clusterConfig: null
  cniprovider: aws-cni
  proxyconfig: {}
  type: eks
---
apiVersion: rafay.io/v1alpha5
iam:
  serviceAccounts:
  - attachPolicy:
      Statement:
      - Action:
        - ec2:DescribeVolumes
        - ec2:DescribeSnapshots
        - ec2:CreateTags
        - ec2:CreateVolume
        - ec2:CreateSnapshot
        - ec2:DeleteSnapshot
        Effect: Allow
        Resource: '*'
      - Action:
        - s3:GetObject
        - s3:DeleteObject
        - s3:PutObject
        - s3:AbortMultipartUpload
        - s3:ListMultipartUploadParts
        Effect: Allow
        Resource:
        - arn:aws:s3:::s3backupbucket/*
      - Action:
        - s3:ListBucket
        Effect: Allow
        Resource:
        - arn:aws:s3:::s3backupbucket
      Version: "2012-10-17"
    metadata:
      name: velero-rafay
      namespace: rafay-system
    roleOnly: true
    roleName: rafay-backuprestore-role
  withOIDC: true
kind: ClusterConfig
metadata:
  name: cluster1
  region: us-west-2
  tags:
  version: "1.21"
managedNodeGroups:
  - name: ng-1
    instanceType: t3.large
    desiredCapacity: 2







