apiVersion: rafay.io/v1alpha1
kind: Cluster
metadata:
  name: azurecluster
  project: poc
spec:
  blueprint: aks-blueprint
  cloudprovider: azure-cloud-credential
  clusterConfig:
    apiVersion: rafay.io/v1alpha1
    kind: aksClusterConfig
    metadata:
      name: azurecluster
    spec:
      managedCluster:
        apiVersion: "2021-05-01"
        identity:
          type: SystemAssigned
        location: azureregion
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: true
          dnsPrefix: azurecluster-dns
          kubernetesVersion: 1.23.8
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
        sku:
          name: Basic
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2021-05-01"
        location: azureregion
        name: primary
        properties:
          count: 2
          enableAutoScaling: false
          maxPods: 40
          mode: System
          orchestratorVersion: 1.23.8
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_DS3_v2
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: azureresourcegroup
  proxyconfig: {}
  type: aks