name: Rafay SOM Deprovision AKS
on:
  push:
    paths:
      - 'aks/deprovision_aks.ps1'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./aks/deprovision_aks.ps1 '${{ secrets.rafaysecret }}'
