name: Rafay EaaS
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./EaaS.ps1 '${{ secrets.rafaysecret }}'