name: Rafay EaaS Provision
on:
  push:
    paths:
      - 'Provision.ps1'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./provision.ps1 '${{ secrets.rafaysecret }}'
