name: Rafay SOM Provision AKS
on:
  push:
    paths:
      - 'aks/provision_aks.ps1'
      - 'aks/cluster/*_custom.yaml'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./aks/provision_aks.ps1 '${{ secrets.rafaysecret }}' '${{ secrets.azuresecret }}'
      - uses: EndBug/add-and-commit@v9