name: Rafay EaaS Provision EKS
on:
  push:
    paths:
      - 'eks/provision_eks.ps1'
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v3
      - run: |
          ./eks/provision_eks.ps1 '${{ secrets.rafaysecret }}'
